#=================================
# Starting image
# https://hub.docker.com/r/budtmo/docker-android-x86-10.0
#=================================
FROM budtmo/docker-android-x86-10.0:latest

USER root

#=======================
# Gopy apk file into container
#=======================
COPY client-retail-qa-2.14.0.apk apps/client-retail-qa-2.14.0.apk